# Generated by Django 5.1.3 on 2024-12-25 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('profiles', '0004_alter_kam_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callfrequency',
            name='last_called',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='interaction_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='callfrequency',
            name='last_call',
            field=models.DateTimeField(blank=True, help_text='The last time a call was made', null=True),
        ),
        migrations.AddField(
            model_name='callfrequency',
            name='next_call',
            field=models.DateTimeField(blank=True, help_text='The next scheduled call', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='date_time',
            field=models.DateTimeField(help_text='Date and time of the interaction', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_order_related',
            field=models.BooleanField(default=False, help_text='Indicates if this interaction is related to an order'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='kam',
            field=models.ForeignKey(help_text='The KAM (Key Account Manager) responsible for this interaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order associated with this interaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='interactions.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(help_text='Date and time of the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(help_text='Unique identifier for the order', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='callfrequency',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], help_text='The frequency of calls', max_length=20),
        ),
        migrations.AlterField(
            model_name='callfrequency',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant this call frequency is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='call_frequencies', to='profiles.restaurant'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(help_text='The contact person involved in the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='profiles.contact'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Meeting', 'Meeting')], help_text='Type of interaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the interaction', null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant this interaction is related to', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='profiles.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant associated with this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Cancelled', 'Cancelled')], default='Pending', help_text='The current status of the order', max_length=20),
        ),
        migrations.DeleteModel(
            name='CallRecord',
        ),
    ]
