# Generated by Django 5.1.3 on 2024-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_remove_callfrequency_last_called_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date_time',
            field=models.DateTimeField(help_text='Date and time of the interaction', null=True, unique=True),
        ),
    ]
