# Generated by Django 5.1.3 on 2024-12-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_alter_interaction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(help_text='Type of interaction', max_length=20),
        ),
    ]
