# Generated by Django 5.1.3 on 2024-12-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_interaction_interaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callfrequency',
            name='frequency',
        ),
        migrations.AddField(
            model_name='callfrequency',
            name='days_between_calls',
            field=models.PositiveIntegerField(help_text='Number of days after which a call should be made', null=True),
        ),
    ]
