# Generated by Django 5.1.3 on 2024-12-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_remove_callfrequency_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='days_between_calls',
            field=models.PositiveIntegerField(default=0, help_text='Number of days after which a call should be made'),
        ),
    ]
