# Generated by Django 5.1.3 on 2024-12-26 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_alter_callfrequency_days_between_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='next_call',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='The next scheduled call'),
        ),
    ]
