# Generated by Django 5.1.3 on 2024-12-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_alter_callfrequency_next_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='days_between_calls',
            field=models.PositiveIntegerField(help_text='Number of days after which a call should be made'),
        ),
        migrations.AlterField(
            model_name='callfrequency',
            name='next_call',
            field=models.DateTimeField(help_text='The next scheduled call'),
        ),
    ]
