# Generated by Django 5.1.3 on 2024-12-26 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_alter_callfrequency_days_between_calls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='last_call',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 26, 9, 39, 57, 813064), help_text='The last time a call was made'),
        ),
    ]
