# Generated by Django 5.1.3 on 2024-12-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_alter_callfrequency_last_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='last_call',
            field=models.DateTimeField(blank=True, help_text='The last time a call was made', null=True),
        ),
    ]
