# Generated by Django 5.1.3 on 2024-12-26 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_alter_callfrequency_last_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='next_call',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 9, 41, 59, 825265), help_text='The next scheduled call'),
        ),
    ]
