# Generated by Django 5.1.3 on 2024-12-26 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0012_alter_callfrequency_next_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='next_call',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The next scheduled call'),
        ),
    ]
