# Generated by Django 5.1.3 on 2024-12-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_alter_callfrequency_next_call'),
        ('profiles', '0004_alter_kam_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfrequency',
            name='restaurant',
            field=models.OneToOneField(help_text='The restaurant this call frequency is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='call_frequencies', to='profiles.restaurant'),
        ),
    ]
