# Generated by Django 5.1.3 on 2024-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0014_alter_callfrequency_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='callfrequency',
            name='next_calls_list',
            field=models.JSONField(default=list, help_text='List of upcoming call dates'),
        ),
    ]
