# Generated by Django 5.1.3 on 2024-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0015_callfrequency_next_calls_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callfrequency',
            name='next_calls_list',
        ),
        migrations.AddField(
            model_name='callfrequency',
            name='next_call_list',
            field=models.JSONField(default=list, help_text='List of (next_call, order_id) pairs'),
        ),
    ]
